[package]
name = "ffmpeg-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.22"
egui = "0.22"
rfd = "0.11"
chrono = "0.4"
image = "0.24"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }